"""AXF v0.1 format constants."""

from __future__ import annotations

AXF_FORMAT_VERSION = "0.1.0"
AXC_FORMAT_VERSION = "0.1.0"
AXP_FORMAT_VERSION = "0.1.0"
AXT_FORMAT_VERSION = "0.1.0"

AXC_EXTENSION = ".axc"
AXC_ZST_EXTENSION = ".axc.zst"
AXP_DIRECTORY_EXTENSION = ".axp"
AXP_ARCHIVE_EXTENSION = ".axp.tar.zst"
AXT_MANIFEST_EXTENSION = ".axt"
AXT_SAFETENSORS_EXTENSION = ".axt.safetensors"
AXSRC_EXTENSION = ".axsrc"
AXR_EXTENSION = ".axr"
AXCTX_EXTENSION = ".axctx"
AXM_EXTENSION = ".axm"

AXF_FORMAT_NAME = "AXF"
AXC_FORMAT_NAME = "AXC"
AXP_FORMAT_NAME = "AXP"
AXT_FORMAT_NAME = "AXT"

SUPPORTED_AXC_EXTENSIONS = (AXC_EXTENSION,)
SPECIFIED_BUT_NOT_IMPLEMENTED_EXTENSIONS = (
    AXC_ZST_EXTENSION,
    AXP_ARCHIVE_EXTENSION,
    AXT_SAFETENSORS_EXTENSION,
)

GAUGE_POLICY_INVARIANT_ONLY = "gauge_invariant_observables_only"
