"""Deterministic provider wrapper around existing Axiom extractors."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from hcaps.extraction.claims import DeterministicClaimExtractor
from hcaps.extraction.contracts import ProviderTrace, SourceSpanRef
from hcaps.ingest.documents import DocumentChunk, SourceDocument
from hcaps.providers.base import ProviderRequest, ProviderResponse, hash_normalized_output
from hcaps.providers.config import ProviderEndpointConfig
from hcaps.substrate.canonicalize import normalize_text, stable_id
from hcaps.substrate.manifest import SubstrateBuildConfig


class DeterministicProvider:
    """Always-available local extraction provider."""

    def __init__(self, config: ProviderEndpointConfig | None = None) -> None:
        self.config = config or ProviderEndpointConfig(
            provider_id="deterministic",
            type="deterministic",
        )
        self.provider_id = self.config.provider_id

    def run(self, request: ProviderRequest) -> ProviderResponse:
        normalized_output: dict[str, Any]
        confidence: float | None
        if request.task == "claim_extraction":
            normalized_output = {"claims": _claim_records(request)}
            confidence = _mean_confidence(normalized_output["claims"])
        elif request.task == "relation_extraction":
            normalized_output = {"relations": [], "candidate_hard_negatives": []}
            confidence = 0.4
        elif request.task == "epistemic_extraction":
            normalized_output = _epistemic_record(request)
            confidence = 0.45
        elif request.task == "structured_view_generation":
            normalized_output = {"views": _structured_views(request), "source_spans_used": []}
            confidence = 0.5
        output_hash = hash_normalized_output(normalized_output)
        trace = _trace(self.config, request, output_hash, confidence)
        return ProviderResponse(
            provider_trace=trace,
            normalized_output=normalized_output,
            confidence=confidence,
            warnings=[],
            raw_response={"provider": "deterministic", "task": request.task},
        )


def _claim_records(request: ProviderRequest) -> list[dict[str, Any]]:
    text = normalize_text(request.input_text)
    if not text:
        return []
    raw_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
    document_id = str(request.source_ref.get("document_id") or stable_id("doc", raw_hash))
    source_id = str(request.source_ref.get("source_id") or stable_id("src", raw_hash))
    document = SourceDocument(
        document_id=document_id,
        source_id=source_id,
        source_path=str(request.source_ref.get("source_path") or "provider-request"),
        file_name=str(request.source_ref.get("file_name") or "provider-request.txt"),
        media_type=str(request.source_ref.get("media_type") or "text/plain"),
        raw_sha256=raw_hash,
        normalized_text_sha256=raw_hash,
        text=text,
        text_length=len(text),
        title=str(request.source_ref.get("title") or "Provider Request"),
        authors=[],
        published_at=None,
        license=str(request.source_ref.get("license") or "unknown"),
        source_url=request.source_ref.get("source_url"),
        domains=list(request.source_ref.get("domains") or []),
        temporal_cutoff_at=None,
        page_number=None,
        reader_name="provider-request",
        reader_version="0.1.0",
    )
    chunk = DocumentChunk(
        chunk_id=stable_id("chunk", document_id, "provider"),
        document_id=document_id,
        source_id=source_id,
        chunk_index=0,
        text=text,
        start_char=0,
        end_char=len(text),
        section_path=[],
    )
    config = SubstrateBuildConfig(
        input_path=Path("."),
        output_path=Path(".deterministic_provider/capsules.jsonl"),
        manifest_path=Path(".deterministic_provider/manifest.json"),
    )
    claims = DeterministicClaimExtractor().extract(chunk, document, config)
    return [
        {
            "text": claim.text,
            "claim_type": claim.claim_type.value,
            "confidence": claim.confidence,
            "source_spans": [
                SourceSpanRef(
                    source_id=source_id,
                    document_id=document_id,
                    start_char=claim.source_start_char,
                    end_char=claim.source_end_char,
                    text=claim.text,
                ).model_dump(mode="json")
            ],
            "notes": f"candidate generated by {claim.extraction_method}",
        }
        for claim in claims
    ]


def _epistemic_record(request: ProviderRequest) -> dict[str, Any]:
    text_length = len(request.input_text)
    source_count = int(request.context.get("source_count") or 1)
    relation_degree = int(request.context.get("relation_degree") or 0)
    disagreement_count = int(request.context.get("provider_disagreement_count") or 0)
    anchoring = min(0.85, 0.35 + 0.1 * source_count)
    uncertainty = max(0.2, min(0.9, 0.7 - 0.05 * source_count + 0.08 * disagreement_count))
    return {
        "ontology_compatibility": _proxy(0.5, "deterministic-neutral-prior", 0.35),
        "evidential_anchoring": _proxy(anchoring, "source-span-presence-proxy", 0.45),
        "transformation_pressure": _proxy(
            min(0.6, relation_degree / 10.0),
            "relation-degree-proxy",
            0.35,
        ),
        "uncertainty": _proxy(uncertainty, "confidence-and-disagreement-proxy", 0.4),
        "independent_redundancy": _proxy(
            float(source_count),
            "distinct-source-effective-count-proxy",
            0.4,
        ),
        "source_count": source_count,
        "provider_disagreement_count": disagreement_count,
        "relation_degree": relation_degree,
        "method_diversity_proxy": 1.0 if request.context.get("provider_ids") else None,
        "source_type_diversity_proxy": None if text_length == 0 else 0.0,
        "benchmark_family_diversity_proxy": None,
    }


def _structured_views(request: ProviderRequest) -> dict[str, str | None]:
    text = " ".join(request.input_text.split())
    summary = text[:280] if text else None
    return {
        "neutral_summary": summary,
        "technical_summary": summary,
        "teaching_note": f"Source-grounded note: {summary}" if summary else None,
        "faq": f"Q: What is claimed?\nA: {summary}" if summary else None,
        "counterargument": None,
        "limitations": "Automatically generated construction view; not human reviewed.",
        "historical_update_or_temporal_note": request.context.get("temporal_note"),
    }


def _proxy(value: float | None, method: str, confidence: float) -> dict[str, Any]:
    return {
        "value": round(value, 3) if isinstance(value, float) else value,
        "method": method,
        "confidence": confidence,
        "notes": "construction proxy, not an evaluation reference",
    }


def _trace(
    config: ProviderEndpointConfig,
    request: ProviderRequest,
    output_hash: str,
    confidence: float | None,
) -> ProviderTrace:
    return ProviderTrace(
        provider_id=config.provider_id,
        provider_type=config.type,
        provider_family=config.provider_family,
        provider_mode=config.provider_mode,
        provider_model=config.model,
        extraction_task=request.task,
        prompt_template_version=request.template_version,
        cache_key=None,
        input_hash=request.input_hash,
        output_hash=output_hash,
        confidence=confidence,
    )


def _mean_confidence(records: list[dict[str, Any]]) -> float | None:
    if not records:
        return 0.0
    return round(sum(float(record["confidence"]) for record in records) / len(records), 3)
